import type { Entity, Template, Workspace } from "./domain";
export const genres = [
  "Folk",
  "Indie Folk",
  "Singer-Songwriter",
  "Indie Rock",
  "Alternative Rock",
  "Shoegaze",
  "Electronic",
  "Ambient",
  "Jazz",
  "Soul",
  "Hip-Hop",
  "Pop",
  "Experimental",
];
export const emotions = [
  "Intimate",
  "Melancholic",
  "Warm",
  "Dreamy",
  "Haunting",
  "Dark",
  "Hopeful",
  "Energetic",
  "Romantic",
  "Reflective",
  "Euphoric",
  "Raw",
];
export const cities = [
  "London",
  "Brighton",
  "Bristol",
  "Manchester",
  "Leeds",
  "Glasgow",
  "Cardiff",
];
export const roleNames = [
  "Promoter",
  "Venue booker",
  "Journalist",
  "Radio presenter",
  "Manager",
  "Booking agent",
  "Producer",
  "Photographer",
];
export const orgTypes = [
  "Record label",
  "Promoter company",
  "Publication",
  "Radio station",
  "Festival",
  "Management company",
  "Booking agency",
  "Recording studio",
];
const rows: [
  string,
  Entity["entity_type"],
  string,
  string,
  string[],
  string[],
  string[],
  string,
][] = [
  [
    "Mosslight Presents",
    "organisation",
    "London",
    "Promoter company",
    ["Promoter"],
    ["Indie Folk", "Singer-Songwriter"],
    ["Intimate", "Warm"],
    "Thoughtful live music in small spaces. Helping emerging artists find their first London audience.",
  ],
  [
    "The Lantern Room",
    "venue",
    "London",
    "",
    ["Venue booker"],
    ["Indie Folk", "Jazz", "Soul"],
    ["Intimate", "Warm"],
    "An independent listening room for quiet discoveries and unforgettable live shows.",
  ],
  [
    "Fern & Field Records",
    "organisation",
    "Bristol",
    "Record label",
    [],
    ["Indie Folk", "Ambient"],
    ["Dreamy", "Reflective"],
    "An artist-led record label drawn to honest songwriting and sounds a little off the beaten path.",
  ],
  [
    "Afterhours Journal",
    "organisation",
    "London",
    "Publication",
    ["Journalist"],
    ["Indie Rock", "Alternative Rock"],
    ["Energetic", "Raw"],
    "New voices, long reads and independent music worth spending time with.",
  ],
  [
    "Low Tide Festival",
    "organisation",
    "Brighton",
    "Festival",
    [],
    ["Indie Folk", "Indie Rock"],
    ["Warm", "Hopeful"],
    "A fictional coastal gathering of independent artists, curious listeners and new ideas.",
  ],
  [
    "Juniper Radio",
    "organisation",
    "Manchester",
    "Radio station",
    ["Radio presenter"],
    ["Electronic", "Ambient", "Indie Folk"],
    ["Dreamy", "Intimate"],
    "Community radio connecting adventurous music with open-minded listeners.",
  ],
  [
    "Rowan Ellis",
    "person",
    "London",
    "",
    ["Promoter"],
    ["Indie Folk", "Singer-Songwriter"],
    ["Intimate", "Melancholic"],
    "Fictional independent promoter working with emerging folk artists across South London.",
  ],
  [
    "Paper Moon Music",
    "organisation",
    "London",
    "Management company",
    ["Manager"],
    ["Indie Folk", "Indie Rock"],
    ["Reflective", "Warm"],
    "A small fictional management company building sustainable artist careers.",
  ],
  [
    "The Copper Works",
    "venue",
    "Bristol",
    "",
    ["Venue booker"],
    ["Indie Rock", "Electronic"],
    ["Energetic", "Raw"],
    "A flexible independent live room with space for bold sounds and new collaborations.",
  ],
  [
    "Northbound Booking",
    "organisation",
    "Leeds",
    "Booking agency",
    ["Booking agent"],
    ["Indie Folk", "Alternative Rock"],
    ["Intimate", "Energetic"],
    "Thoughtfully routed tours for independent artists finding their next audience.",
  ],
  [
    "Soft Focus Studio",
    "organisation",
    "Glasgow",
    "Recording studio",
    ["Producer"],
    ["Ambient", "Shoegaze"],
    ["Dreamy", "Haunting"],
    "A fictional recording space for texture, experimentation and patient music making.",
  ],
  [
    "Morgan Vale",
    "person",
    "Brighton",
    "",
    ["Journalist"],
    ["Indie Folk", "Soul"],
    ["Warm", "Reflective"],
    "Fictional writer exploring songwriting, independent releases and the people behind them.",
  ],
  [
    "Orchard Sessions",
    "organisation",
    "London",
    "Promoter company",
    ["Promoter"],
    ["Folk", "Indie Folk"],
    ["Intimate", "Melancholic"],
    "Stripped-back performances from emerging songwriters in welcoming neighbourhood spaces.",
  ],
  [
    "Wild Current",
    "artist_project",
    "Cardiff",
    "",
    [],
    ["Indie Rock", "Shoegaze"],
    ["Energetic", "Dreamy"],
    "A fictional artist project included to demonstrate the canonical music-industry graph.",
  ],
  [
    "Sunday Signal",
    "organisation",
    "London",
    "Radio station",
    ["Radio presenter"],
    ["Jazz", "Soul", "Hip-Hop"],
    ["Warm", "Reflective"],
    "Independent radio with a soft spot for new voices and carefully made records.",
  ],
  [
    "Glasshouse Live",
    "organisation",
    "Manchester",
    "Promoter company",
    ["Promoter"],
    ["Indie Rock", "Alternative Rock"],
    ["Raw", "Energetic"],
    "Grassroots shows that put emerging artists at the centre of the room.",
  ],
  [
    "Stillwater Sounds",
    "organisation",
    "London",
    "Record label",
    [],
    ["Ambient", "Electronic"],
    ["Dreamy", "Haunting"],
    "A fictional home for quietly adventurous electronic music.",
  ],
  [
    "The Assembly Cellar",
    "venue",
    "Leeds",
    "",
    ["Venue booker"],
    ["Folk", "Indie Folk"],
    ["Intimate", "Warm"],
    "A small fictional venue with a listening audience and an open door for emerging talent.",
  ],
];
export const entities: Entity[] = rows.map((r, i) => ({
  id: `10000000-0000-4000-8000-${String(i + 1).padStart(12, "0")}`,
  display_name: r[0],
  entity_type: r[1],
  location: r[2],
  organisation_type: r[3],
  roles: r[4],
  genres: r[5],
  emotions: r[6],
  description: r[7],
  organisation:
    r[1] === "person"
      ? i === 6
        ? "Mosslight Presents"
        : "Afterhours Journal"
      : "",
  email: `hello@${r[0].toLowerCase().replace(/[^a-z]/g, "")}.example`,
  website: "",
  verification_status: "unverified",
  submission_status: i % 4 === 3 ? "closed" : "open",
  submission_type:
    r[3] === "Record label"
      ? "demo"
      : r[3] === "Publication"
        ? "press"
        : r[3] === "Radio station"
          ? "radio"
          : "booking",
  submission_instructions:
    "Demo submission guidance: introduce your project, share one listening link, and explain why the fit feels right. These are fictional records; no mail is delivered.",
  aliases: [r[0].replace("The ", "")],
  source: "MusicMail synthetic demo dataset",
  source_url: "",
  verified_at: null,
  capacity: r[1] === "venue" ? 120 + i * 10 : null,
}));
export const defaultTemplates: Template[] = [
  {
    id: "20000000-0000-4000-8000-000000000001",
    name: "A first introduction",
    category: "Promoter introduction",
    subject: "{{artist_name}} — a little introduction",
    body: "Hi {{first_name}},\n\nI’m reaching out from {{artist_name}}. I love what you’re building at {{organisation}} and thought our music might be a good fit.\n\n[Add a personal connection and one listening link.]\n\nWould you be open to a conversation?\n\nThanks for listening,\n{{artist_name}}",
  },
  {
    id: "20000000-0000-4000-8000-000000000002",
    name: "A gentle follow-up",
    category: "Follow-up",
    subject: "Following up — {{artist_name}}",
    body: "Hi {{first_name}},\n\nJust following up on my last note. I know things get busy, so no pressure at all.\n\n[Add a useful update or a specific question.]\n\nAll the best,\n{{artist_name}}",
  },
  {
    id: "20000000-0000-4000-8000-000000000003",
    name: "A record for your ears",
    category: "Label demo",
    subject: "New music from {{artist_name}}",
    body: "Hi {{first_name}},\n\nI’m sharing a new release from {{artist_name}} for consideration at {{organisation}}.\n\n[Add one private listening link and a short description of the music.]\n\nThank you for your time,\n{{artist_name}}",
  },
];
export function demoWorkspace(): Workspace {
  return {
    demo: true,
    email: "Demo workspace",
    artistName: "Your artist project",
    onboarded: false,
    isAdmin: false,
    contacts: [],
    notes: [],
    interactions: [],
    lists: [],
    members: [],
    views: [],
    templates: structuredClone(defaultTemplates),
    sent: [],
    gmailEmail: null,
    goals: [],
  };
}
