-- Canonical entity graph and owner-scoped CRM. Migration 001.
create extension if not exists pg_trgm;
create extension if not exists pgcrypto;
create table public.admin_users (user_id uuid primary key references auth.users on delete cascade);
create function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from admin_users where user_id=auth.uid()) $$;
create table public.locations (id uuid primary key default gen_random_uuid(), country_code text not null default 'GB', country_name text not null default 'United Kingdom', region text, city text, neighbourhood text, postcode text, latitude numeric, longitude numeric, slug text unique);
create table public.organisation_types (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, description text);
create table public.venue_types (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, description text);
create table public.roles (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, description text);
create table public.relationship_types (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, description text);
create table public.emotion_families (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, description text);
create table public.genres (id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, parent_genre_id uuid references genres);
create table public.emotions (id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, family_id uuid references emotion_families);
create table public.entities (id uuid primary key default gen_random_uuid(), entity_type text not null check(entity_type in ('person','organisation','artist_project','venue')), display_name text not null check(length(trim(display_name)) between 1 and 200), slug text unique, description text, primary_location_id uuid references locations, visibility text not null default 'public' check(visibility in ('public','private')), verification_status text not null default 'unverified' check(verification_status in ('unverified','verified','potentially_outdated','disputed')), created_by uuid references auth.users on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz);
create table public.people (entity_id uuid primary key references entities on delete cascade, first_name text, last_name text, preferred_name text);
create table public.organisations (entity_id uuid primary key references entities on delete cascade, organisation_type_id uuid references organisation_types, parent_organisation_id uuid references organisations(entity_id), website_domain text, scale text);
create table public.artist_projects (entity_id uuid primary key references entities on delete cascade, artist_type text not null, career_stage text, active boolean not null default true);
create table public.venues (entity_id uuid primary key references entities on delete cascade, venue_type_id uuid references venue_types, capacity_min integer check(capacity_min>=0), capacity_max integer check(capacity_max>=capacity_min), address_line_1 text, address_line_2 text, postcode text, layout_type text, age_restriction text, accessibility_notes text, green_room boolean, backline_available boolean, typical_artist_level text);
create table public.entity_roles (id uuid primary key default gen_random_uuid(), entity_id uuid not null references entities on delete cascade, role_id uuid not null references roles, organisation_id uuid references entities, started_at date, ended_at date, is_current boolean not null default true, unique(entity_id,role_id,organisation_id));
create table public.entity_relationships (id uuid primary key default gen_random_uuid(), source_entity_id uuid not null references entities on delete cascade, target_entity_id uuid not null references entities on delete cascade, relationship_type_id uuid not null references relationship_types, started_at date, ended_at date, is_current boolean not null default true, created_at timestamptz default now(), updated_at timestamptz default now(), check(source_entity_id<>target_entity_id), unique(source_entity_id,target_entity_id,relationship_type_id));
create table public.entity_locations (entity_id uuid references entities on delete cascade, location_id uuid references locations, relationship_type text not null default 'based_in', primary key(entity_id,location_id,relationship_type));
create table public.entity_genres (entity_id uuid references entities on delete cascade, genre_id uuid references genres, primary key(entity_id,genre_id));
create table public.entity_emotions (entity_id uuid references entities on delete cascade, emotion_id uuid references emotions, primary key(entity_id,emotion_id));
create table public.entity_contact_methods (id uuid primary key default gen_random_uuid(), entity_id uuid not null references entities on delete cascade, contact_type text not null, label text, value text not null, purpose text, is_primary boolean default false, is_public boolean not null default true, is_verified boolean default false, last_verified_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now(), unique(entity_id,id));
create table public.submission_channels (id uuid primary key default gen_random_uuid(), entity_id uuid not null references entities on delete cascade, submission_type text not null, status text not null default 'unknown' check(status in ('open','closed','unknown')), email_contact_method_id uuid, submission_url text, opens_at timestamptz, closes_at timestamptz, instructions text, fee_amount numeric check(fee_amount>=0), fee_currency text, last_verified_at timestamptz, foreign key(entity_id,email_contact_method_id) references entity_contact_methods(entity_id,id));
create table public.entity_aliases (id uuid primary key default gen_random_uuid(), entity_id uuid not null references entities on delete cascade, alias text not null, normalised_alias text not null, unique(entity_id,normalised_alias));
create table public.entity_sources (id uuid primary key default gen_random_uuid(), entity_id uuid not null references entities on delete cascade, source_type text, source_name text, source_url text, retrieved_at timestamptz default now(), verified_at timestamptz);
create table public.profiles (id uuid primary key references auth.users on delete cascade, display_name text, timezone text default 'Europe/London', country text, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.user_preferences (user_id uuid primary key references auth.users on delete cascade, primary_artist_entity_id uuid references entities on delete set null, goals jsonb not null default '[]', onboarding_completed boolean default false, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.user_contacts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade default auth.uid(), entity_id uuid references entities on delete set null, private_display_name text, private_email text, private_details jsonb not null default '{}', relationship_status text not null default 'unknown' check(relationship_status in ('unknown','cold','contacted','warm','familiar','met_personally','worked_together','strong_relationship')), outreach_status text not null default 'not_contacted' check(outreach_status in ('not_contacted','draft','sent','replied','interested','declined','follow_up_needed','completed','no_response','do_not_contact')), priority text check(priority in ('low','medium','high')), relationship_origin text, first_contacted_at timestamptz, last_contacted_at timestamptz, follow_up_at date, archived boolean not null default false, created_at timestamptz default now(), updated_at timestamptz default now(), unique(user_id,entity_id), unique(user_id,id), check(entity_id is not null or length(trim(private_display_name))>0));
create table public.notes (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade default auth.uid(), user_contact_id uuid not null, body text not null check(length(trim(body)) between 1 and 20000), pinned boolean default false, created_at timestamptz default now(), updated_at timestamptz default now(), foreign key(user_id,user_contact_id) references user_contacts(user_id,id) on delete cascade);
create table public.interactions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade default auth.uid(), user_contact_id uuid not null, type text not null, title text not null, metadata jsonb, occurred_at timestamptz default now(), created_at timestamptz default now(), foreign key(user_id,user_contact_id) references user_contacts(user_id,id) on delete cascade);
create table public.saved_views (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade default auth.uid(), name text not null, filter_definition jsonb not null default '{}', sort_definition jsonb default '{}', visible_columns jsonb default '[]', created_at timestamptz default now(), updated_at timestamptz default now());
create table public.lists (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade default auth.uid(), name text not null, created_at timestamptz default now(), unique(user_id,id));
create table public.list_members (user_id uuid not null references auth.users on delete cascade default auth.uid(), list_id uuid not null, user_contact_id uuid not null, primary key(list_id,user_contact_id), foreign key(user_id,list_id) references lists(user_id,id) on delete cascade, foreign key(user_id,user_contact_id) references user_contacts(user_id,id) on delete cascade);
create table public.email_templates (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade default auth.uid(), name text not null, category text, subject text not null, body text not null, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.sent_emails (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, user_contact_id uuid not null, gmail_message_id text, recipient text not null, subject text not null, body text not null, sent_at timestamptz default now(), foreign key(user_id,user_contact_id) references user_contacts(user_id,id) on delete cascade);
create table public.gmail_connections (user_id uuid primary key references auth.users on delete cascade, email text not null, encrypted_tokens text not null, updated_at timestamptz default now());
create table public.email_send_attempts (id uuid primary key, user_id uuid not null references auth.users on delete cascade, user_contact_id uuid not null, status text not null default 'reserved' check(status in ('reserved','sent','failed','uncertain')), created_at timestamptz default now(), foreign key(user_id,user_contact_id) references user_contacts(user_id,id) on delete cascade);
create function public.can_read_entity(eid uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from entities where id=eid and ((visibility='public' and archived_at is null) or created_by=auth.uid() or is_admin())) $$;
alter table public.locations enable row level security;
create policy shared_read on public.locations for select to authenticated using (true);
create policy admin_write on public.locations for all to authenticated using (is_admin()) with check (is_admin());
grant select,insert,update,delete on public.locations to authenticated;
grant all on public.locations to service_role;
alter table public.organisation_types enable row level security;
create policy shared_read on public.organisation_types for select to authenticated using (true);
create policy admin_write on public.organisation_types for all to authenticated using (is_admin()) with check (is_admin());
grant select,insert,update,delete on public.organisation_types to authenticated;
grant all on public.organisation_types to service_role;
alter table public.venue_types enable row level security;
create policy shared_read on public.venue_types for select to authenticated using (true);
create policy admin_write on public.venue_types for all to authenticated using (is_admin()) with check (is_admin());
grant select,insert,update,delete on public.venue_types to authenticated;
grant all on public.venue_types to service_role;
alter table public.roles enable row level security;
create policy shared_read on public.roles for select to authenticated using (true);
create policy admin_write on public.roles for all to authenticated using (is_admin()) with check (is_admin());
grant select,insert,update,delete on public.roles to authenticated;
grant all on public.roles to service_role;
alter table public.relationship_types enable row level security;
create policy shared_read on public.relationship_types for select to authenticated using (true);
create policy admin_write on public.relationship_types for all to authenticated using (is_admin()) with check (is_admin());
grant select,insert,update,delete on public.relationship_types to authenticated;
grant all on public.relationship_types to service_role;
alter table public.emotion_families enable row level security;
create policy shared_read on public.emotion_families for select to authenticated using (true);
create policy admin_write on public.emotion_families for all to authenticated using (is_admin()) with check (is_admin());
grant select,insert,update,delete on public.emotion_families to authenticated;
grant all on public.emotion_families to service_role;
alter table public.genres enable row level security;
create policy shared_read on public.genres for select to authenticated using (true);
create policy admin_write on public.genres for all to authenticated using (is_admin()) with check (is_admin());
grant select,insert,update,delete on public.genres to authenticated;
grant all on public.genres to service_role;
alter table public.emotions enable row level security;
create policy shared_read on public.emotions for select to authenticated using (true);
create policy admin_write on public.emotions for all to authenticated using (is_admin()) with check (is_admin());
grant select,insert,update,delete on public.emotions to authenticated;
grant all on public.emotions to service_role;
alter table public.people enable row level security;
create policy shared_read on public.people for select to authenticated using (can_read_entity(entity_id));
create policy admin_write on public.people for all to authenticated using (is_admin()) with check (is_admin());
grant select,insert,update,delete on public.people to authenticated;
grant all on public.people to service_role;
alter table public.organisations enable row level security;
create policy shared_read on public.organisations for select to authenticated using (can_read_entity(entity_id));
create policy admin_write on public.organisations for all to authenticated using (is_admin()) with check (is_admin());
grant select,insert,update,delete on public.organisations to authenticated;
grant all on public.organisations to service_role;
alter table public.artist_projects enable row level security;
create policy shared_read on public.artist_projects for select to authenticated using (can_read_entity(entity_id));
create policy admin_write on public.artist_projects for all to authenticated using (is_admin()) with check (is_admin());
grant select,insert,update,delete on public.artist_projects to authenticated;
grant all on public.artist_projects to service_role;
alter table public.venues enable row level security;
create policy shared_read on public.venues for select to authenticated using (can_read_entity(entity_id));
create policy admin_write on public.venues for all to authenticated using (is_admin()) with check (is_admin());
grant select,insert,update,delete on public.venues to authenticated;
grant all on public.venues to service_role;
alter table public.entity_roles enable row level security;
create policy shared_read on public.entity_roles for select to authenticated using (can_read_entity(entity_id));
create policy admin_write on public.entity_roles for all to authenticated using (is_admin()) with check (is_admin());
grant select,insert,update,delete on public.entity_roles to authenticated;
grant all on public.entity_roles to service_role;
alter table public.entity_locations enable row level security;
create policy shared_read on public.entity_locations for select to authenticated using (can_read_entity(entity_id));
create policy admin_write on public.entity_locations for all to authenticated using (is_admin()) with check (is_admin());
grant select,insert,update,delete on public.entity_locations to authenticated;
grant all on public.entity_locations to service_role;
alter table public.entity_genres enable row level security;
create policy shared_read on public.entity_genres for select to authenticated using (can_read_entity(entity_id));
create policy admin_write on public.entity_genres for all to authenticated using (is_admin()) with check (is_admin());
grant select,insert,update,delete on public.entity_genres to authenticated;
grant all on public.entity_genres to service_role;
alter table public.entity_emotions enable row level security;
create policy shared_read on public.entity_emotions for select to authenticated using (can_read_entity(entity_id));
create policy admin_write on public.entity_emotions for all to authenticated using (is_admin()) with check (is_admin());
grant select,insert,update,delete on public.entity_emotions to authenticated;
grant all on public.entity_emotions to service_role;
alter table public.entity_contact_methods enable row level security;
create policy shared_read on public.entity_contact_methods for select to authenticated using (can_read_entity(entity_id) and (is_public or is_admin()));
create policy admin_write on public.entity_contact_methods for all to authenticated using (is_admin()) with check (is_admin());
grant select,insert,update,delete on public.entity_contact_methods to authenticated;
grant all on public.entity_contact_methods to service_role;
alter table public.submission_channels enable row level security;
create policy shared_read on public.submission_channels for select to authenticated using (can_read_entity(entity_id));
create policy admin_write on public.submission_channels for all to authenticated using (is_admin()) with check (is_admin());
grant select,insert,update,delete on public.submission_channels to authenticated;
grant all on public.submission_channels to service_role;
alter table public.entity_aliases enable row level security;
create policy shared_read on public.entity_aliases for select to authenticated using (can_read_entity(entity_id));
create policy admin_write on public.entity_aliases for all to authenticated using (is_admin()) with check (is_admin());
grant select,insert,update,delete on public.entity_aliases to authenticated;
grant all on public.entity_aliases to service_role;
alter table public.entity_sources enable row level security;
create policy shared_read on public.entity_sources for select to authenticated using (can_read_entity(entity_id));
create policy admin_write on public.entity_sources for all to authenticated using (is_admin()) with check (is_admin());
grant select,insert,update,delete on public.entity_sources to authenticated;
grant all on public.entity_sources to service_role;
alter table public.user_preferences enable row level security;
create policy owner_access on public.user_preferences for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
grant select,insert,update,delete on public.user_preferences to authenticated;
grant all on public.user_preferences to service_role;
alter table public.user_contacts enable row level security;
create policy owner_access on public.user_contacts for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
grant select,insert,update,delete on public.user_contacts to authenticated;
grant all on public.user_contacts to service_role;
alter table public.notes enable row level security;
create policy owner_access on public.notes for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
grant select,insert,update,delete on public.notes to authenticated;
grant all on public.notes to service_role;
alter table public.interactions enable row level security;
create policy owner_access on public.interactions for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
grant select,insert,update,delete on public.interactions to authenticated;
grant all on public.interactions to service_role;
alter table public.saved_views enable row level security;
create policy owner_access on public.saved_views for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
grant select,insert,update,delete on public.saved_views to authenticated;
grant all on public.saved_views to service_role;
alter table public.lists enable row level security;
create policy owner_access on public.lists for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
grant select,insert,update,delete on public.lists to authenticated;
grant all on public.lists to service_role;
alter table public.list_members enable row level security;
create policy owner_access on public.list_members for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
grant select,insert,update,delete on public.list_members to authenticated;
grant all on public.list_members to service_role;
alter table public.email_templates enable row level security;
create policy owner_access on public.email_templates for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
grant select,insert,update,delete on public.email_templates to authenticated;
grant all on public.email_templates to service_role;
alter table public.entities enable row level security;
create policy shared_read on public.entities for select to authenticated using (can_read_entity(id));
create policy admin_write on public.entities for all to authenticated using (is_admin()) with check (is_admin());
grant select,insert,update,delete on public.entities to authenticated;
grant all on public.entities to service_role;
alter table public.entity_relationships enable row level security;
create policy shared_read on public.entity_relationships for select to authenticated using (can_read_entity(source_entity_id) and can_read_entity(target_entity_id));
create policy admin_write on public.entity_relationships for all to authenticated using (is_admin()) with check (is_admin());
grant select,insert,update,delete on public.entity_relationships to authenticated;
grant all on public.entity_relationships to service_role;
alter table public.profiles enable row level security;
create policy owner_access on public.profiles for all to authenticated using (id=auth.uid()) with check (id=auth.uid());
grant select,insert,update,delete on public.profiles to authenticated;
grant all on public.profiles to service_role;
alter table public.admin_users enable row level security;
grant all on public.admin_users to service_role;
alter table public.gmail_connections enable row level security;
grant all on public.gmail_connections to service_role;
alter table public.email_send_attempts enable row level security;
grant all on public.email_send_attempts to service_role;
alter table public.sent_emails enable row level security;
create policy owner_read on public.sent_emails for select to authenticated using(user_id=auth.uid());
grant select,insert,update,delete on public.sent_emails to authenticated;
grant all on public.sent_emails to service_role;
revoke insert,update,delete on public.sent_emails from authenticated;
create index entities_name_trgm on entities using gin(display_name gin_trgm_ops);
create index aliases_name_trgm on entity_aliases using gin(normalised_alias gin_trgm_ops);
create index entities_type on entities(entity_type);
create index organisations_type on organisations(organisation_type_id);
create index contacts_followup on user_contacts(user_id,follow_up_at) where not archived;
create index contacts_status on user_contacts(user_id,relationship_status,outreach_status);
create index contacts_last on user_contacts(user_id,last_contacted_at);
create index send_attempts_rate on email_send_attempts(user_id,created_at);
create index entity_roles_filter on entity_roles(role_id,entity_id);
create index entity_roles_entity on entity_roles(entity_id);
create index entity_genres_filter on entity_genres(genre_id,entity_id);
create index entity_genres_entity on entity_genres(entity_id);
create index entity_emotions_filter on entity_emotions(emotion_id,entity_id);
create index entity_emotions_entity on entity_emotions(entity_id);
create index entity_locations_filter on entity_locations(location_id,entity_id);
create index entity_locations_entity on entity_locations(entity_id);
create index entity_contact_methods_filter on entity_contact_methods(contact_type,entity_id);
create index entity_contact_methods_entity on entity_contact_methods(entity_id);
create index notes_contact on notes(user_id,user_contact_id);
create index interactions_contact on interactions(user_id,user_contact_id);
create index sent_emails_contact on sent_emails(user_id,user_contact_id);
create function public.contact_history() returns trigger language plpgsql security definer set search_path=public as $$ begin
 if TG_OP='INSERT' then insert into interactions(user_id,user_contact_id,type,title) values(new.user_id,new.id,'contact_added','Added to your network');
 else
 if new.relationship_status is distinct from old.relationship_status then insert into interactions(user_id,user_contact_id,type,title) values(new.user_id,new.id,'relationship_changed','Relationship: '||replace(new.relationship_status,'_',' ')); end if;
 if new.outreach_status is distinct from old.outreach_status then insert into interactions(user_id,user_contact_id,type,title) values(new.user_id,new.id,'outreach_status_changed','Outreach: '||replace(new.outreach_status,'_',' ')); end if;
 if new.follow_up_at is distinct from old.follow_up_at then insert into interactions(user_id,user_contact_id,type,title) values(new.user_id,new.id,'follow_up_changed','Follow-up updated'); end if;
 end if; return new; end $$;
create trigger contacts_history after insert or update on user_contacts for each row execute function contact_history();
create function public.note_history() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into interactions(user_id,user_contact_id,type,title) values(new.user_id,new.user_contact_id,'note_added','Private note added'); return new; end $$;
create trigger notes_history after insert on notes for each row execute function note_history();
create function public.complete_onboarding(project_name text, project_type text, city_name text, genre_names text[], emotion_names text[], user_goals jsonb) returns uuid language plpgsql security definer set search_path=public as $$
declare eid uuid; lid uuid; begin
 if auth.uid() is null then raise exception 'Authentication required'; end if;
 if length(trim(project_name)) not between 1 and 200 or project_type not in ('solo','band','duo','collective','producer_project','dj_project','other') then raise exception 'Invalid artist'; end if;
 select primary_artist_entity_id into eid from user_preferences where user_id=auth.uid();
 select id into lid from locations where city=city_name limit 1;
 if eid is null then
 insert into entities(entity_type,display_name,visibility,created_by,primary_location_id) values('artist_project',trim(project_name),'private',auth.uid(),lid) returning id into eid;
 insert into artist_projects(entity_id,artist_type) values(eid,project_type);
 else
 if not exists(select 1 from entities where id=eid and created_by=auth.uid()) then raise exception 'Invalid owner'; end if;
 update entities set display_name=trim(project_name),primary_location_id=lid,updated_at=now() where id=eid;
 update artist_projects set artist_type=project_type where entity_id=eid;
 delete from entity_genres where entity_id=eid; delete from entity_emotions where entity_id=eid;
 end if;
 insert into entity_genres select eid,id from genres where name=any(genre_names);
 insert into entity_emotions select eid,id from emotions where name=any(emotion_names);
 insert into profiles(id,display_name) values(auth.uid(),project_name) on conflict(id) do update set display_name=excluded.display_name;
 insert into user_preferences(user_id,primary_artist_entity_id,goals,onboarding_completed) values(auth.uid(),eid,user_goals,true) on conflict(user_id) do update set goals=excluded.goals,onboarding_completed=true;
 return eid; end $$;
revoke all on function complete_onboarding(text,text,text,text[],text[],jsonb) from public;
grant execute on function complete_onboarding(text,text,text,text[],text[],jsonb) to authenticated;
